#!/usr/bin/env ruby

# Copyright 2021 Ismo Kärkkäinen
# Licensed under Universal Permissive License. See LICENSE.txt.

require './unittest.rb'

$unit_test = 0
load '../lib/common.rb'

$context = 'aargh'
assert(aargh("string").nil?, true, 'String, nil')
assert(aargh([ 1, 2 ], 2), 2, 'Array, 2')

exit $unit_test
