#!/usr/bin/env ruby

# Copyright 2021 Ismo Kärkkäinen
# Licensed under Universal Permissive License. See LICENSE.txt.

require './unittest.rb'

$unit_test = 0
load '../bin/diagrammatron-prune'

$context = 'prune_array'
assert(prune_array([1, 2], [false, true], false), [1], 'Kept non-matching 1')
assert(prune_array([1, 2], [true, false], false), [2], 'Kept non-matching 2')
assert(prune_array([1, 2], [false, true], true), [2], 'Kept matching 2')
assert(prune_array([1, 2], [true, false], true), [1], 'Kept matching 1')

exit $unit_test
