#!/usr/bin/env ruby

# Copyright 2021 Ismo Kärkkäinen
# Licensed under Universal Permissive License. See License.txt.

$unit_test = 0
load '../diagrammatron-prune'

$context = ''
def assert(value, expected, message)
  condition = value == expected
  $stdout.puts("#{condition ? 'ok' : 'fail'}: #{$context}: #{message}")
  $stderr.puts("#{value.to_s} != #{expected.to_s}") unless condition
  $unit_test = 1 unless condition
  return condition
end

$context = 'prune_array'
assert(prune_array([1, 2], [false, true], false), [1], 'Kept non-matching 1')
assert(prune_array([1, 2], [true, false], false), [2], 'Kept non-matching 2')
assert(prune_array([1, 2], [false, true], true), [2], 'Kept matching 2')
assert(prune_array([1, 2], [true, false], true), [1], 'Kept matching 1')

exit $unit_test
