AllCops:
  NewCops: enable

Layout/ArgumentAlignment:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyLines:
  Enabled: false
Layout/FirstHashElementIndentation:
  Enabled: false
Layout/LineLength:
  Enabled: false
Layout/MultilineArrayBraceLayout:
  Enabled: false
Layout/MultilineMethodCallBraceLayout:
  Enabled: false
Layout/MultilineOperationIndentation:
  Enabled: false
Layout/ParameterAlignment:
  Enabled: false
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Layout/SpaceInsideReferenceBrackets:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: false
Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

Naming/BinaryOperatorParameterName:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false

Security/Eval:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false
Style/CombinableLoops:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Style/RedundantParentheses:
  Enabled: false
Style/RedundantPercentQ:
  Enabled: false
Style/SoleNestedConditional:
  Enabled: false
Style/StderrPuts:
  Enabled: false
Style/TernaryParentheses:
  Enabled: false
Style/UnlessElse:
  Enabled: false
Style/YodaCondition:
  Enabled: false

Style/Documentation:
  Enabled: false
